### ISSUE TITLE
Connect signatures and WH connections

### ISSUE THREAD

**Issue by arne-klein** [marbindrakon/eve-wspace#119] opened 2015-01-08 01:49 UTC
Hi,
are there any plans on creating a logical connection between the signature IDs and the corresponding WH connections? So that deleting a WH signature would for example automatically get rid of the correspoding connection.

**Comment by marbindrakon** [comment] 2015-01-17 19:53
Closing this as a duplicate of #118

**Closed by marbindrakon** 2015-01-17 19:53 UTC
